"""initial tables

Revision ID: 44f443b54011
Revises: 
Create Date: 2025-10-11 21:59:20.211599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f443b54011'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coa_id_group',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('access_token', sa.String(length=32), nullable=True),
    sa.Column('access_expiration', sa.DateTime(), nullable=True),
    sa.Column('refresh_token', sa.String(length=32), nullable=True),
    sa.Column('refresh_expiration', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_access_token'), 'account', ['access_token'], unique=True)
    op.create_index(op.f('ix_account_refresh_token'), 'account', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_account_user_id'), 'account', ['user_id'], unique=False)
    op.create_table('coa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['coa_id_group.group_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coa_group_id'), 'coa', ['group_id'], unique=False)
    op.create_table('new_vendor_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_descr', sa.String(length=500), nullable=False),
    sa.Column('proposed_vendor', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_new_vendor_request_user_id'), 'new_vendor_request', ['user_id'], unique=False)
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('model_name', sa.String(length=256), nullable=False),
    sa.Column('coa_group_id', sa.Integer(), nullable=False),
    sa.Column('published', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['coa_group_id'], ['coa_id_group.group_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name')
    )
    op.create_index(op.f('ix_template_coa_group_id'), 'template', ['coa_group_id'], unique=False)
    op.create_index(op.f('ix_template_id'), 'template', ['id'], unique=False)
    op.create_table('user_coa_access',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['coa_id_group.group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_index(op.f('ix_user_coa_access_group_id'), 'user_coa_access', ['group_id'], unique=False)
    op.create_index(op.f('ix_user_coa_access_user_id'), 'user_coa_access', ['user_id'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('account', sa.String(length=256), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_template_id'), 'transaction', ['template_id'], unique=False)
    op.create_table('user_template_access',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('template_id', 'user_id')
    )
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=256), nullable=False),
    sa.Column('transaction_descr', sa.String(length=500), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_template_id'), 'vendor', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_template_id'), table_name='vendor')
    op.drop_table('vendor')
    op.drop_table('user_template_access')
    op.drop_index(op.f('ix_transaction_template_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_user_coa_access_user_id'), table_name='user_coa_access')
    op.drop_index(op.f('ix_user_coa_access_group_id'), table_name='user_coa_access')
    op.drop_table('user_coa_access')
    op.drop_index(op.f('ix_template_id'), table_name='template')
    op.drop_index(op.f('ix_template_coa_group_id'), table_name='template')
    op.drop_table('template')
    op.drop_index(op.f('ix_new_vendor_request_user_id'), table_name='new_vendor_request')
    op.drop_table('new_vendor_request')
    op.drop_index(op.f('ix_coa_group_id'), table_name='coa')
    op.drop_table('coa')
    op.drop_index(op.f('ix_account_user_id'), table_name='account')
    op.drop_index(op.f('ix_account_refresh_token'), table_name='account')
    op.drop_index(op.f('ix_account_access_token'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('coa_id_group')
    # ### end Alembic commands ###
