"""initial tables

Revision ID: a3ff76026cbd
Revises: 
Create Date: 2025-12-15 11:58:12.593890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ff76026cbd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coa_id_group',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('image', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('access_token', sa.String(length=32), nullable=True),
    sa.Column('access_expiration', sa.DateTime(), nullable=True),
    sa.Column('refresh_token', sa.String(length=32), nullable=True),
    sa.Column('refresh_expiration', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_access_token'), 'account', ['access_token'], unique=True)
    op.create_index(op.f('ix_account_refresh_token'), 'account', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_account_user_id'), 'account', ['user_id'], unique=False)
    op.create_table('coa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['coa_id_group.group_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coa_group_id'), 'coa', ['group_id'], unique=False)
    op.create_table('coa_extension',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coa_group', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['coa_group'], ['coa_id_group.group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'coa_group')
    )
    op.create_index(op.f('ix_coa_extension_coa_group'), 'coa_extension', ['coa_group'], unique=False)
    op.create_index(op.f('ix_coa_extension_user_id'), 'coa_extension', ['user_id'], unique=False)
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('model_name', sa.String(length=256), nullable=False),
    sa.Column('base_coa_group', sa.Integer(), nullable=False),
    sa.Column('published', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['base_coa_group'], ['coa_id_group.group_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name')
    )
    op.create_index(op.f('ix_template_id'), 'template', ['id'], unique=False)
    op.create_table('user_coa_access',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['coa_id_group.group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_index(op.f('ix_user_coa_access_group_id'), 'user_coa_access', ['group_id'], unique=False)
    op.create_index(op.f('ix_user_coa_access_user_id'), 'user_coa_access', ['user_id'], unique=False)
    op.create_table('template_coa_mapping_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('coa_group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['coa_group_id'], ['coa_id_group.group_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'user_id', 'coa_group_id', 'name', name='uq_template_user_coa_mapping')
    )
    op.create_index(op.f('ix_template_coa_mapping_group_coa_group_id'), 'template_coa_mapping_group', ['coa_group_id'], unique=False)
    op.create_index(op.f('ix_template_coa_mapping_group_template_id'), 'template_coa_mapping_group', ['template_id'], unique=False)
    op.create_index(op.f('ix_template_coa_mapping_group_user_id'), 'template_coa_mapping_group', ['user_id'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('account', sa.String(length=256), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_template_id'), 'transaction', ['template_id'], unique=False)
    op.create_table('user_template_access',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('template_id', 'user_id')
    )
    op.create_table('coa_translation',
    sa.Column('mapping_group_id', sa.Integer(), nullable=False),
    sa.Column('base_coa_id', sa.Integer(), nullable=False),
    sa.Column('translated_coa_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('base_coa_id != translated_coa_id', name='check_no_self_mapping'),
    sa.ForeignKeyConstraint(['base_coa_id'], ['coa.id'], ),
    sa.ForeignKeyConstraint(['mapping_group_id'], ['template_coa_mapping_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['translated_coa_id'], ['coa.id'], ),
    sa.PrimaryKeyConstraint('mapping_group_id', 'base_coa_id')
    )
    op.create_index(op.f('ix_coa_translation_mapping_group_id'), 'coa_translation', ['mapping_group_id'], unique=False)
    op.create_index(op.f('ix_coa_translation_translated_coa_id'), 'coa_translation', ['translated_coa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coa_translation_translated_coa_id'), table_name='coa_translation')
    op.drop_index(op.f('ix_coa_translation_mapping_group_id'), table_name='coa_translation')
    op.drop_table('coa_translation')
    op.drop_table('user_template_access')
    op.drop_index(op.f('ix_transaction_template_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_template_coa_mapping_group_user_id'), table_name='template_coa_mapping_group')
    op.drop_index(op.f('ix_template_coa_mapping_group_template_id'), table_name='template_coa_mapping_group')
    op.drop_index(op.f('ix_template_coa_mapping_group_coa_group_id'), table_name='template_coa_mapping_group')
    op.drop_table('template_coa_mapping_group')
    op.drop_index(op.f('ix_user_coa_access_user_id'), table_name='user_coa_access')
    op.drop_index(op.f('ix_user_coa_access_group_id'), table_name='user_coa_access')
    op.drop_table('user_coa_access')
    op.drop_index(op.f('ix_template_id'), table_name='template')
    op.drop_table('template')
    op.drop_index(op.f('ix_coa_extension_user_id'), table_name='coa_extension')
    op.drop_index(op.f('ix_coa_extension_coa_group'), table_name='coa_extension')
    op.drop_table('coa_extension')
    op.drop_index(op.f('ix_coa_group_id'), table_name='coa')
    op.drop_table('coa')
    op.drop_index(op.f('ix_account_user_id'), table_name='account')
    op.drop_index(op.f('ix_account_refresh_token'), table_name='account')
    op.drop_index(op.f('ix_account_access_token'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('coa_id_group')
    # ### end Alembic commands ###
