"""initial

Revision ID: 34db972264d7
Revises: 
Create Date: 2025-07-07 10:18:52.147532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34db972264d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coai_dto_group',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('coa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['coai_dto_group.group_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coa_group_id'), ['group_id'], unique=False)

    op.create_table('new_vendor_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_descr', sa.String(length=500), nullable=False),
    sa.Column('proposed_vendor', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('new_vendor_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_new_vendor_requests_user_id'), ['user_id'], unique=False)

    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('model_name', sa.String(length=256), nullable=False),
    sa.Column('coa_group_id', sa.Integer(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.id'], ),
    sa.ForeignKeyConstraint(['coa_group_id'], ['coai_dto_group.group_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name')
    )
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_template_coa_group_id'), ['coa_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_template_id'), ['id'], unique=False)

    op.create_table('user_coa_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['coai_dto_group.group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_coa_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_coa_access_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_coa_access_user_id'), ['user_id'], unique=False)

    op.create_table('marketplace_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketplace_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_tags_tag'), ['tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_tags_template_id'), ['template_id'], unique=False)

    op.create_table('marketplace_template',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('template_id')
    )
    with op.batch_alter_table('marketplace_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_template_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_template_template_id'), ['template_id'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('account', sa.String(length=256), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_template_id'), ['template_id'], unique=False)

    op.create_table('user_template_access',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('template_id', 'user_id')
    )
    with op.batch_alter_table('user_template_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_template_access_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_template_access_user_id'), ['user_id'], unique=False)

    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=256), nullable=False),
    sa.Column('transaction_descr', sa.String(length=500), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_template_id'), ['template_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_template_id'))

    op.drop_table('vendor')
    with op.batch_alter_table('user_template_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_template_access_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_template_access_template_id'))

    op.drop_table('user_template_access')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_template_id'))

    op.drop_table('transaction')
    with op.batch_alter_table('marketplace_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_template_template_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_template_price'))

    op.drop_table('marketplace_template')
    with op.batch_alter_table('marketplace_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_tags_template_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_tags_tag'))

    op.drop_table('marketplace_tags')
    with op.batch_alter_table('user_coa_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_coa_access_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_coa_access_group_id'))

    op.drop_table('user_coa_access')
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_id'))
        batch_op.drop_index(batch_op.f('ix_template_coa_group_id'))
        batch_op.drop_index(batch_op.f('ix_template_author'))

    op.drop_table('template')
    with op.batch_alter_table('new_vendor_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_new_vendor_requests_user_id'))

    op.drop_table('new_vendor_requests')
    with op.batch_alter_table('coa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coa_group_id'))

    op.drop_table('coa')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_token'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('coai_dto_group')
    # ### end Alembic commands ###
